// <auto-generated />
namespace Domain.SurveySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Question_QType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Question_QType));
        
        string IMigrationMetadata.Id
        {
            get { return "202103291404067_Question_QType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
